networks:
  iternal:
    name: iternal
  exposed:
    name: exposed
services:
  jvm:
    build: ./jvm
    volumes:
      - ./jvm/dist:/opt/application
      - ./jvm/home:/home
    networks:
      - iternal
      - exposed
    depends_on:
      - maria
    entrypoint: /bin/bash /home/startup.sh
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/home:/home
    networks:
      - exposed
    depends_on:
      - jvm
    entrypoint: /bin/bash /home/startup.sh
  maria:
    build: ./mariadb
    volumes:
      - ./mariadb/home:/home
      - ./mariadb/start_dump:/docker-entrypoint-initdb.d
    networks:
      - iternal